module.exports = Object.freeze({
    ZBEUB: './Amine Mojito - Zbeub zbeub.mp3',
    KEVIN: './kevin1.mp3',
    MLGHORN: './mlg-airhorn.mp3',
    ROSA: './rosa.mp3',
    AYOU: './ayou.mp3',
    BRUH: './bruh.mp3',
    GASP: './AnimeGasp.mp3',

    GENRES: [
        { key: 'action', value: 1 },
        { key: 'adventure', value: 2 },
        { key: 'cars', value: 3 },
        { key: 'comedy', value: 4 },
        { key: 'dementia', value: 5 },
        { key: 'demons', value: 6 },
        { key: 'mystery', value: 7 },
        { key: 'drama', value: 8 },
        { key: 'ecchi', value: 9 },
        { key: 'fantasy', value: 10 },
        { key: 'game', value: 11 },
        { key: 'game', value: 12 },
        { key: 'game', value: 13 },
        { key: 'game', value: 14 },
        { key: 'game', value: 15 },
        { key: 'game', value: 16 },
        { key: 'game', value: 17 },
        { key: 'game', value: 18 },
        { key: 'game', value: 19 },
        { key: 'game', value: 20 },
        { key: 'game', value: 21 },
        { key: 'game', value: 22 },
        { key: 'game', value: 23 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 25 },
        { key: 'romance', value: 26 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
        { key: 'romance', value: 24 },
    ]
});