module.exports = Object.freeze({
    SOUNDS: [
        {  key: 'zbeub', filePath: './mp3s/zbeub.mp3' },
        {  key: 'ayou', filePath: './mp3s/ayou.mp3' },
        {  key: 'bruh', filePath: './mp3s/bruh.mp3' },
        {  key: 'kevin', filePath: './mp3s/kevin.mp3' },
        {  key: 'rosa', filePath: './mp3s/rosa.mp3' },
        {  key: 'haun', filePath: './mp3s/haun.mp3' },
        {  key: 'highiq', filePath: './mp3s/highiq.mp3' },
        {  key: 'wallacox', filePath: './mp3s/wallacox.mp3' },
        {  key: 'maxime', filePath: './mp3s/maxime.mp3' },
        {  key: 'xplik', filePath: './mp3s/xplik.mp3' },
        {  key: 'gasp', filePath: './mp3s/gasp.mp3' },
        {  key: 'md', filePath: './mp3s/md.mp3' }
    ],

    GENRES: [
        { key: 'action', value: 1 },
        { key: 'adventure', value: 2 },
        { key: 'cars', value: 3 },
        { key: 'comedy', value: 4 },
        { key: 'dementia', value: 5 },
        { key: 'demons', value: 6 },
        { key: 'mystery', value: 7 },
        { key: 'drama', value: 8 },
        { key: 'ecchi', value: 9 },
        { key: 'fantasy', value: 10 },
        { key: 'game', value: 11 },
        { key: 'hentai', value: 12 },
        { key: 'historical', value: 13 },
        { key: 'horror', value: 14 },
        { key: 'kids', value: 15 },
        { key: 'magic', value: 16 },
        { key: 'martial arts', value: 17 },
        { key: 'mecha', value: 18 },
        { key: 'music', value: 19 },
        { key: 'parody', value: 20 },
        { key: 'samurai', value: 21 },
        { key: 'romance', value: 22 },
        { key: 'school', value: 23 },
        { key: 'scifi', value: 24 },
        { key: 'shoujo', value: 25 },
        { key: 'shoujouai', value: 26 },
        { key: 'shounen', value: 27 },
        { key: 'shounenai', value: 28 },
        { key: 'space', value: 29 },
        { key: 'sports', value: 30 },
        { key: 'superpower', value: 31 },
        { key: 'vampire', value: 32 },
        { key: 'yaoi', value: 33 },
        { key: 'yuri', value: 34 },
        { key: 'harem', value: 35 },
        { key: 'sliceoflife', value: 36 },
        { key: 'supernatural', value: 37 },
        { key: 'military', value: 38 },
        { key: 'police', value: 39 },
        { key: 'psychological', value: 40 },
        { key: 'thriller', value: 41 },
        { key: 'seinen', value: 42 },
        { key: 'josei', value: 43 }
    ]
});