resource_types:
- name: git
  type: registry-image
  source:
    repository: concourse/git-resource
    tag: ubuntu

resource_types:
- name: s3-bucket
  type: docker-image
  source:
    repository: troykinsella/s3-resource-simple

resources:
- name: repo
  type: git
  icon: github
  source:
    uri: ((git-src-uri))
    branch: master
    private_key: ((git-private-key))

- name: tasks
  check_every: 2m
  type: git
  icon: github
  source:
    uri: ((git-tasks-uri))
    branch: master
    private_key: ((git-private-key))

- name: configs
  check_every: 2m
  type: git
  icon: github
  source:
    uri: ((git-configs-uri))
    branch: master
    private_key: ((git-private-key))

- name: my-bucket
  type: s3-bucket
  icon: aws
  source:
    bucket: ((bucket_name))
    versioned_file: ((path-s3))
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))  
    region_name: ((region_name))


jobs:
- name: deploy-to-bucket
  serial: true
  plan:
  - get: repo 
  - get: configs
  - put: my-bucket

- name: release
  plan: 
  - get: repo
  - get: tasks
  - get: configs
    passed: [deploy-to-bucket]
  - task: connect-to-ec2
    file: tasks/connect_ec2.yml

