resource_types:
- name: git
  type: registry-image
  source:
    repository: concourse/git-resource
    tag: ubuntu

resource_types:
- name: s3-bucket
  type: docker-image
  source:
    repository: troykinsella/s3-resource-simple

resources:
- name: repo
  check_every: 2m
  type: git
  icon: github
  source:
    uri: ((git-uri))
    branch: ((git-branch))
    private_key: ((git-private-key))
    
- name: my-bucket
  type: s3-bucket
  icon: aws
  source:
    bucket: ((bucket_name))
    versioned_file: ((path-s3))
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))  
    region_name: ((region_name))

# - name: node-image
#   type: registry-image
#   source:
#     repository: node
#     tag: 13.10.1-stretch

jobs:
- name: deploy-to-bucket
  public: true
  plan:
  - get: repo 
    trigger: true
  - put: my-bucket
  # - task: install
  #   image: node-image
  #   config:
  #     inputs:
  #     - name: repo
  #     outputs:
  #     - name: dependencies
  #       path: repo/node_modules
  #     platform: linux
  #     run:
  #       path: npm
  #       args: ["install"]
  #       dir: repo
  # - task: extract
